export const constants = {
  SHOW_LOADER: "SHOW_LOADER",
  HIDE_LOADER: "HIDE_LOADER",

  SIGNIN_REQUEST: "SIGNIN_REQUEST",
  SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
  SIGNIN_FAILURE: "SIGNIN_FAILURE",

  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",

  SIGN_OUT: "SIGN_OUT",

  //POST CONSTSNTS

  LOAD_ALL_POSTS_SUCCESS: "LOAD_ALL_POSTS_SUCCESS",
  LOAD_USER_POSTS_SUCCESS: "LOAD_USER_POSTS_SUCCESS",

  CREATE_POST_REQUEST: "CREATE_POST_REQUEST",
  CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
  CREATE_POST_FAILURE: "CREATE_POST_FAILURE",

  LIKE_UNLIKE_POST_SUCCESS: "LIKE_UNLIKE_POST_SUCCESS",
  ADD_COMMENT_SUCCESS: "ADD_COMMENT_SUCCESS",
  DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
};
